# Generated by Django 3.1.7 on 2021-06-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210608_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='aboutus',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='contactus',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='references',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpemail',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtppassword',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpport',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpserver',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='title',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='twitter',
        ),
        migrations.AddField(
            model_name='setting',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setting',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='New', max_length=10),
        ),
    ]
