# Generated by Django 3.1.7 on 2021-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210701_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='questionnumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
